#!/bin/bash
GIT_TERMINAL_PROMPT=0
git config --global user.name spin-ci
git config --global user.email spin@ci
LATEST="$(GIT_TERMINAL_PROMPT=0 git ls-remote https://github.com/raspberrypi/linux | grep -oE "rpi-[0-9].*?[.][0-9].*?[.]y" | sort -rV | head -n2 | tail -n1)"
# LATEST="stable"
git clone https://github.com/raspberrypi/linux "linux-$LATEST"
cd linux-$LATEST
git checkout $(git branch -a --format="%(refname:short)" | grep -v "^origin" | sort -u | grep -oE "rpi-[0-9].*?[.][0-9].*?[.]y" | sort -rV | head -n2 | tail -n1)
KVER="$(git branch | sed "s/-/_/g")"
cd ..
rm -fr "linux-$LATEST/.git" "linux-$LATEST/.github" "linux-$LATEST/.gitignore" "linux-$LATEST/.gitattributes"
tar czvf "linux.tar.gz" "linux-$LATEST"
echo "linux-$LATEST" > kernel-version
echo linux_$KVER_$(date +%Y%m%d%H%M) > package-version
mkdir rpms
mkdir -p ffr-kernel{,-devicetree,-headers,-modules,-overlays,-source}/{root,rpm}
TARGETS="ffr-kernel ffr-kernel-devicetree ffr-kernel-headers ffr-kernel-modules ffr-kernel-overlays ffr-kernel-source"
for target in $TARGETS; do
	cp ../specs/$target.spec $target
done
