#!/bin/bash
GIT_TERMINAL_PROMPT=0
LATEST="rpi-6.17.y"
git clone --depth=1 --single-branch --branch "$LATEST" https://github.com/raspberrypi/linux "linux-$LATEST"
rm -fr "linux-$LATEST/.git" "linux-$LATEST/.github" "linux-$LATEST/.gitignore" "linux-$LATEST/.gitattributes"
tar czf "linux.tar.gz" "linux-$LATEST"
echo "linux-$LATEST" > kernel-version
echo linux_$(date +%Y%m%d%H%M) > package-version
mkdir rpms
mkdir -p ffr-kernel{,-devicetree,-headers,-modules,-overlays,-source}/{root,rpm}
TARGETS="ffr-kernel ffr-kernel-devicetree ffr-kernel-headers ffr-kernel-modules ffr-kernel-overlays ffr-kernel-source"
for target in $TARGETS; do
	cp ../specs/$target.spec $target
done
